"""Add parts table

Revision ID: 3c14390b617a
Revises: 6f285e6dd2b8
Create Date: 2025-10-31 09:06:06.334542+00:00

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3c14390b617a"
down_revision = "6f285e6dd2b8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("specifications", sa.JSON(), nullable=True),
        sa.Column("current_stock", sa.Integer(), nullable=False),
        sa.Column("minimum_stock", sa.Integer(), nullable=False),
        sa.Column(
            "unit_price", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_parts_category"), "parts", ["category"], unique=False
    )
    op.create_index(op.f("ix_parts_name"), "parts", ["name"], unique=False)
    op.create_index(op.f("ix_parts_sku"), "parts", ["sku"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parts_sku"), table_name="parts")
    op.drop_index(op.f("ix_parts_name"), table_name="parts")
    op.drop_index(op.f("ix_parts_category"), table_name="parts")
    op.drop_table("parts")
    # ### end Alembic commands ###
